export default {
    "APP_STARTED": "APP_STARTED",
    "APP_STARTING": "APP_STARTING",
    "CLEARED_TOKENS": "CLEARED_TOKENS",
    "FETCHED_TOKENS": "FETCHED_TOKENS",
    "FETCHED_USERPROFILE": "FETCHED_USERPROFILE",
    "FETCHING_TOKENS": "FETCHING_TOKENS",
    "GETTING_IDENTITY": "GETTING_IDENTITY",
    "GETTING_TOKENS": "GETTING_TOKENS",
    "GOT_IDENTITY": "GOT_IDENTITY",
    "GOT_TOKENS": "GOT_TOKENS",
    "SET_USERPROFILE": "SET_USERPROFILE",
    "SHOW_ERROR": "SHOW_ERROR",
    "SHOW_TOAST": "SHOW_TOAST"
};