export default {
    "APP_STARTED": "APP_STARTED",
    "APP_STARTING": "APP_STARTING",
    "FETCHED_TOKENS": "FETCHED_TOKENS",
    "FETCHING_TOKENS": "FETCHING_TOKENS",
    "SHOW_ERROR": "SHOW_ERROR",
    "SHOW_TOAST": "SHOW_TOAST"
};