# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd $(Build.SourcesDirectory)/functions
    yarn install
    mkdir $(Build.BinariesDirectory)/nodejs
    cp -r node_modules $(Build.BinariesDirectory)/nodejs
  displayName: 'Pack and copy nodejs dependencies'

- script: |
    cd $(Build.SourcesDirectory)/functions
    yarn test
    zip -r $(Build.ArtifactStagingDirectory)/nyc_cov_$(Build.BuildNumber).zip ./coverage/*  
  displayName: 'Run unit tests'

- script: |
    cd $(Build.SourcesDirectory)/functions
    zip -r functions_package_$(Build.BuildNumber).zip . -x node_modules\* 
    cp functions_package_$(Build.BuildNumber).zip $(Build.ArtifactStagingDirectory)
  displayName: 'Pack and copy functions code'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/nodejs'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/node_package_$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/iac'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/iac_package_$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'tamtam_api_build'
    publishLocation: 'Container'
